#apiVersion: storage.k8s.io/v1
#kind: StorageClass
#metadata:
#  name: myfirst-storageclass
#provisioner: efs.csi.aws.com
#volumeBindingMode: WaitForFirstConsumer

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: myfirst-storageclass
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
