apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: aws-ebs-sc
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: "vol-0ff23756d2b3369f8"
    fsType: ext4  

